### ISSUE TITLE
高性能体现在哪？

### ISSUE THREAD

**Issue by watsy0007** [zqhong/route#5]
有benchmark吗？

**Comment by zqhong** [comment]
# 路由性能测试
## 环境
Vultr 1核1G 配置 LAMP

## 测试命令
ab -n 2000 -c 10 http://localhost/xxx_route.php

## 测试结果：
symfony route（symfony/routing - v3.2.5）
Requests per second:    783.61 [#/sec] (mean)

zqhong route（zqhong/route - dev）
Requests per second:    810.18 [#/sec] (mean)

nikic_route（nikic/fast-route - v1.2.0）
Requests per second:    669.73 [#/sec] (mean)

**Comment by zqhong** [comment]
@watsy0007 稍后我把测试代码放上来

**Comment by zqhong** [comment]
@watsy0007 测试代码和测试结果请看 benchmark 目录。README.md 也更新了相应的性能测试说明。
